List<Map> productList=[
  {
    "name":'Hospital Professional Doctor Wear Hi Vis Medical white Lab Coat',
    "category":'Medical',
    "headerURL":'images/products/lab_coat.jpg',
    "oldPrice":2000,
    "price":1599.99,
    "avgRate":4.5,
    "totalRates":234,
    'totalFiveStar':35,
    'stockAvailable':40,
    'location':'Kathmandu',
    "detailURL":'file/products/medical_lab_coat.html',
    "images":['images/products/lab_coat.jpg','images/products/lab_coat.jpg','images/products/lab_coat.jpg',],
  },
  {
    "name":'Mens Shirt Embroidery Printing Long Sleeve Shirt',
    "category":'Men Fashion',
    "headerURL":'images/products/sleeveShirt.jpg',
    'location':'Bhaktapur',
    "oldPrice":2500,
    "price":1399.99,
    "stockAvailable":25,
    "avgRate":4.0,
    "totalRates":224,
    'totalFiveStar':45,
    "detailURL":'file/products/medical_lab_coat.html',
    "images":['images/products/lab_coat.jpg','images/products/lab_coat.jpg','images/products/lab_coat.jpg',],

  },
  {
    "name":'Women Jogging Suit Tracksuit Sports Tracksuit for Women',
    "category":'Women Fashion',
    "headerURL":'images/products/wJoggingTrack.jfif',
    'location':"Lalitpur",
    "oldPrice":2100,
    "price":1299.99,
    'stockAvailable':10,
    "avgRate":4.2,
    "totalRates":230,
    'totalFiveStar':30,
    "detailURL":'file/products/medical_lab_coat.html',
    "images":['images/products/lab_coat.jpg','images/products/lab_coat.jpg','images/products/lab_coat.jpg',],

  }
];